spring.application.name=AbsherApp
spring.datasource.url=jdbc:mysql://localhost:3306/absherdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Mohammed@050785

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true